services:
  - type: web
    name: n8n-odoo
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: TZ
        value: Europe/Berlin
      - key: N8N_HOST
        sync: false
      - key: N8N_PROTOCOL
        value: https
      - key: DATA_FOLDER
        value: /home/node/.n8n/data